# Generated by Django 4.2.1 on 2023-05-10 05:17

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.avatar_path),
        ),
    ]
