# Generated by Django 4.2.1 on 2023-06-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_position_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultants', to='accounts.position'),
        ),
    ]
