# Generated by Django 4.2.1 on 2023-06-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_blog_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
    ]
