# Generated by Django 4.2.1 on 2023-06-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_postimage_image_remove_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='', upload_to='posts/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='post.post'),
        ),
    ]
