# Generated by Django 4.2.1 on 2023-06-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author_blog_type_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='type',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
