# Generated by Django 4.2.1 on 2023-06-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_media_is_deleted_message_is_deleted_room_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
