# Generated by Django 4.2.1 on 2023-06-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_chatmember_remove_message_room_message_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
    ]
